### ISSUE TITLE
训练自己的数据集出错

### ISSUE THREAD

**Issue by Rentong2022** [McGregorWwww/UCTransNet#40]
作者您好。我想使用该网络训练自己的数据集，并按照原格式命名自己的数据集。我的数据集图片大小为1024×1024，我在Config.py文件中修改了img_size为1024，也修改了task_name 为自己的数据集名字，其他的都未修改，但是出现了以下问题：
Traceback (most recent call last):
  File "C:\Users\o\Desktop\UCTransNet-main\train_model.py", line 191, in <module>
    model = main_loop(model_type=config.model_name, tensorboard=True)
  File "C:\Users\o\Desktop\UCTransNet-main\train_model.py", line 139, in main_loop
    train_one_epoch(train_loader, model, criterion, optimizer, writer, epoch, None, model_type, logger)
  File "C:\Users\o\Desktop\UCTransNet-main\Train_one_epoch.py", line 54, in train_one_epoch
    for i, (sampled_batch, names) in enumerate(loader, 1):
  File "D:\anaconda\envs\rt\lib\site-packages\torch\utils\data\dataloader.py", line 652, in __next__
    data = self._next_data()
  File "D:\anaconda\envs\rt\lib\site-packages\torch\utils\data\dataloader.py", line 1347, in _next_data
    return self._process_data(data)
  File "D:\anaconda\envs\rt\lib\site-packages\torch\utils\data\dataloader.py", line 1373, in _process_data
    data.reraise()
  File "D:\anaconda\envs\rt\lib\site-packages\torch\_utils.py", line 461, in reraise
    raise exception
cv2.error: Caught error in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "D:\anaconda\envs\rt\lib\site-packages\torch\utils\data\_utils\worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "D:\anaconda\envs\rt\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\anaconda\envs\rt\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\o\Desktop\UCTransNet-main\Load_Dataset.py", line 152, in __getitem__
    mask = cv2.resize(mask,(self.image_size,self.image_size))
cv2.error: OpenCV(3.4.16-dev) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\resize.cpp:4051: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'
您能解答一下我的问题吗，谢谢您。

**Comment by McGregorWwww** [comment]
你好，这个问题是因为mask路径错了，没有正确读入，可以参考：https://blog.csdn.net/weixin_43358444/article/details/83217902

**Comment by Rentong2022** [comment]
谢谢您，我还想问一下该网络对数据集格式的要求，只能是png格式吗，因为我自己的数据集格式为jpg,我感觉可能是自己数据集格式问题。

**Comment by McGregorWwww** [comment]
jpg格式也是没问题的，不过要确保image是RGB 3通道，mask是灰度 1通道。

**Comment by Rentong2022** [comment]
您好，我检查的图片的格式都没有问题，我想请问一下该网络的最大输入图像大小是多少，因为我的图像大小是1024×1024，是不是输入数据集太大了，谢谢您。

**Comment by McGregorWwww** [comment]
你好，根据你之前提供的错误日志，错误出现在读取图片这一步，还没有到送入网络这一环节，所以还是图片读取的问题，建议在resize之前输出一下mask的shape，max，min等信息检查一下

**Comment by qym77** [comment]
我也有同样的问题，我其实都没有改代码，怕路径出错等，我直接在测试集的两个中分别加上了自己数据集原图和mask，然后运行test_model.py 想看一下效果也是这个问题

**Comment by McGregorWwww** [comment]
你好，可以输出一下image id看看是哪张图报的错，有可能是image没有对应的mask，或者mask文件损坏，代码应该是没有问题的

**Comment by qym77** [comment]
是的，您的代码非常neat！优美又简洁！只是我初学水平有点弱TT，如果您能添加一个替换自己数据集的指导更好了，当然没有也没关系十分感谢您的工作！

**Comment by McGregorWwww** [comment]
感谢你的建议！我在README里面更新了一下如何替换自己的数据集，希望有帮助
